### ISSUE TITLE
would this work with ember data?

### ISSUE THREAD

**Issue by danielspaniel** [bengillies/ember-parallel#3]
Hi Ben, 
 I am looking for a way to stop the UI from freezing in my ember application when I load a pile of data through ember data.  I am thinking that it is not quite possible because the web worker might not have access to models, store etc.. but maybe I am wrong? 

   I want to run something like: 

```js
    var versions = this.get('project.versions');
    Em.RSVP.all(versions.invoke('reload')).then(function () {
     versions.invoke('setupFunctions');
    });
```

 Would the data be loaded properly .. not sure? I could use computed property .. but not sure exactly how.  Any ideas that cross you mind would be super appreciated :)

**Comment by runspired** [comment]
@danielspaniel in terms of non-locking ui, general tips here: https://github.com/runspired/smoke-and-mirrors.

My adapter and serializer simply send their requests into / out of the worker. They have access to localStorage, but not the store.  You largely have to define any needed model knowledge etc in the worker up front.

**Comment by danielspaniel** [comment]
Those were some good tips @runspired .. thanks.  
How exactly do you send requests to an adapter or serializer in/out of web worker?  The puzzles me a bit.

**Comment by runspired** [comment]
Via `postMessage`.  On some systems you can transfer objects but usually you need to stringify.  For example, in your adapter's find method you send a message with a unique ID and the request details to the worker, which performs the request, normalizes the data, caches it to local storage, and then sends a message back via postMessage with the normalized payload and containing that uniqueId.  You still need to push into store, but you no longer have any of the heavy lifting to do.

If you want some in depth help on this find DM in the ember slack forum and I can dig in.

**Comment by runspired** [comment]
If you can get away with using a live array as the model, the worker could trim the find request response down to just a few records, and in a separate series of `postMessage`s deliver the rest to avoid processing them all at once.

**Comment by danielspaniel** [comment]
Hmm .. that is kinda of a good idea .. about having the data sent to local storage and then picking it up from there and putting into the store.  Your ideas have given me something to chew on besides my fingernails. Thanks.

**Comment by bengillies** [comment]
Hi Daniel. to be honest, I've not done much Ember stuff for ~1 year or so now (I don't get much chance sadly), but did run into exactly the issue that you mention. At the time, the best/easiest solution was to ditch Ember Data completely and use Ember Model instead, which was a _lot_ faster.

**Comment by danielspaniel** [comment]
Stuck with ember-data for now ( its such a big project .. can't switch too soon ).   For now I am making liberal use of the phrase "Go get some coffee while you data is loading"That was good suggestion though, because I know ember model is way faster.   


     On Monday, March 30, 2015 4:29 AM, Ben Gillies <notifications@github.com> wrote:
   

 Hi Daniel. to be honest, I've not done much Ember stuff for ~1 year or so now (I don't get much chance sadly), but did run into exactly the issue that you mention. At the time, the best/easiest solution was to ditch Ember Data completely and use Ember Model instead, which was a lot faster.—

**Comment by runspired** [comment]
@danielspaniel if you do switch, look at ember-orbit.  Perf-wise, I don't find ember-data itself to be slow at all, I just find it to have all sorts of other rough edges.  Dev-wise, yeah, ED's rough edges can really slow you down sometimes.  The changes to make various find/fetch queries explicit will really help with that.

**Comment by danielspaniel** [comment]
ember-orbit seems really nice. I think I might go with that one day ( when the money is rolling in ) .. because I am going to need those features in orbit ( offline and syncing among clients )  and I don't mind so much if ember-data is slow per se, I just wanted to load things in the background and keep the ui responsive ..  
 


     On Monday, March 30, 2015 4:46 PM, Chris Thoburn <notifications@github.com> wrote:
   

 @danielspaniel if you do switch, look at ember-orbit. Perf-wise, I don't find ember-data itself to be slow at all, I just find it to have all sorts of other rough edges. Dev-wise, yeah, ED's rough edges can really slow you down sometimes. The changes to make various find/fetch queries explicit will really help with that.—

**Comment by bengillies** [comment]
IIRC it was the state machine and relationship stuff that caused me the biggest issues with performance before. The issue I think is that Ember Data really isn't designed to be a high performance library, it's designed to be an easy to use, feature-ful library instead. You might try removing all of your relationships perhaps and handling them manually if you can't switch out to something else (I can't guarantee this will improve things much though)?

Good luck. Anyway, I'm closing the issue now, but feel free to raise more issues if you do find a use for ember-parallel - as I say, I'm not doing much ember at the moment - so I won't be able to find/fix any issues if any exist without bug reports.

You might also try #emberjs on IRC freenode.
